name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  nb-sync:
    env:
      HOME: /root
    runs-on: ubuntu-latest
    container: fastai/jekyll
    steps:
    - uses: actions/checkout@v2
    - run: pip install -qe .
    - name: Check if notebooks are synced and cleaned
      uses: fastai/workflows/nb@master

  nbdev_test_nbs:
    strategy:
      fail-fast: false
      matrix:
        os:  [ubuntu, windows]
        py:  [3.6, 3.7, 3.8]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}
    - name: Setup Environment
      run: |
        pip install git+https://github.com/fastai/fastcore.git
        pip install -qe .
    - name: Run tests
      run: make test

  fastpages-integration:
    env:
      HOME: /root
    runs-on: ubuntu-latest
    container: fastai/jekyll
    steps:
    - uses: actions/checkout@v2
    - name: Install nbdev
      run: |
        pip install -qe .
        pip install -qU fastcore   
    - uses: actions/checkout@v2
      with:
        repository: "fastai/fastpages"
        path: "data"
    - name: convert posts  
      run: |
        cd data
        mkdir -p /fastpages
        cp -r _action_files/* /fastpages/
        /fastpages/action_entrypoint.sh
  
