name: publish-release
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master
env:
  HOME: /root
jobs:
  build:
    if: |
      (github.event_name == 'workflow_dispatch') || 
      (github.event_name == 'push' && (github.event.head_commit.author.username == 'github-actions[bot]') && contains(github.event.head_commit.message, 'Update CHANGELOG.md'))
    runs-on: ubuntu-latest
    container: fastai/miniconda
    steps:
    - uses: actions/checkout@v2
    - uses: fastai/workflows/conda-env@master
    - name: Create condarc
      run: |
        cat >> ~/.condarc << EOF
        conda-build:
          anaconda_token: fa-5a8ca5e3-3c13-4260-8a54-362fa83d91f6
        EOF
        pip install anaconda-cli twine
    - uses: fastai/fastrelease/action/publish@master
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
